apiVersion: v1
kind: ConfigMap
metadata:
  name: pms-config
data:

  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/mydb

 
  SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
  
  
  SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: "30000"
  SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: "10000"
  SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: "30000"